"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu, X } from "lucide-react";
import { useState } from "react";
import { motion } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}) {
  const [open, setOpen] = useState(false);
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white`}
      >
        {/* Navbar */}
      <nav className="fixed w-full top-0 left-0 z-50 bg-black/40 backdrop-blur-md shadow-md">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          {/* Logo */}
          <div className="text-2xl font-bold tracking-wide text-white">
            🚀 MiLogo
          </div>

          {/* Links Desktop */}
          <div className="hidden md:flex gap-8">
            <a href="#home" className="hover:text-blue-400 transition">Inicio</a>
            <a href="#features" className="hover:text-blue-400 transition">Características</a>
            <a href="#contact" className="hover:text-blue-400 transition">Contacto</a>
          </div>

          {/* Botón Hamburguesa */}
          <button
            className="md:hidden text-white"
            onClick={() => setOpen(!open)}
          >
            {open ? <X size={28} /> : <Menu size={28} />}
          </button>
        </div>

        {/* Menú Móvil */}
        {open && (
          <motion.div
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="md:hidden bg-black/90 px-6 py-4 flex flex-col gap-4"
          >
            <a href="#home" className="hover:text-blue-400 transition">Inicio</a>
            <a href="#features" className="hover:text-blue-400 transition">Características</a>
            <a href="#contact" className="hover:text-blue-400 transition">Contacto</a>
          </motion.div>
        )}
      </nav>
        {children}
      </body>
    </html>
  );
}
